# Lambda function

In [15]:
x = lambda a : a + 10

print(x(5))

15


In [16]:
x = lambda a, b : a * b
print(x(6, 7))

42


In [17]:
def myfunc(n):
    return lambda a : a * n

mydoubler = myfunc(2)

mydoubler(13)

26

## Numpy code along


In [18]:
# 'np' is the conventional alias for numpy
import numpy as np

#### Numpy arrays

In [19]:
## one dimensional array is a vector
a = np.array([5,3,2])

In [20]:
a.shape

(3,)

#### Generate an array with random numbers

In [21]:
np.random.seed(1002)
a = np.random.random((6,2))
a

array([[0.12898829, 0.46115618],
       [0.41615393, 0.60272423],
       [0.18306805, 0.41791271],
       [0.13408871, 0.65661813],
       [0.80673232, 0.13814196],
       [0.35038474, 0.61451581]])

### Other ways to create arrays

#### List to array

This works the same way whether you have a list of lists, a list of tuples, a tuple of lists, or a tuple of tuples.

In [22]:
lst_lst_lst = [[[1,2,3],[4,5,6],[7,8,9]]]
d = np.array(lst_lst_lst)
print(d.shape)

(1, 3, 3)


#### Constant arrays

In [23]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a, "\n")

b = np.ones((3,2))   # Create an array of all ones
print(b, "\n")

c = np.full((2,2), 7) # Create a constant array
print(c)

[[0. 0.]
 [0. 0.]] 

[[1. 1.]
 [1. 1.]
 [1. 1.]] 

[[7 7]
 [7 7]]


#### Sequential arrays

In [24]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [26]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 1.85402874,  0.49396181, -0.13071143],
       [-0.40312075, -0.97366226, -0.46746678],
       [-0.71792147,  1.22139331, -0.77720001]])

In [27]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[7, 1, 3],
       [5, 9, 9],
       [2, 7, 5]])

#### Array Attributes

In [28]:
np.random.seed(123)
a = np.random.random((6,3))
a

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971],
       [0.43857224, 0.0596779 , 0.39804426],
       [0.73799541, 0.18249173, 0.17545176]])

In [29]:
a.shape

(6, 3)

In [30]:
a.size

18

In [31]:
a.ndim

2

In [32]:
a.dtype

dtype('float64')

In [33]:
b = np.array([1,3,8])

In [34]:
b.dtype

dtype('int64')

In [35]:
b.astype(np.int8)

array([1, 3, 8], dtype=int8)

In [36]:
b.itemsize

8

In [37]:
c = np.array([1,3,4], dtype="int8") # smaller integers

In [38]:
c.itemsize

1

In [39]:
c = np.array([1,3,4]).astype(np.int8)

In [40]:
c

array([1, 3, 4], dtype=int8)

In [41]:
new_array = np.array([1,2,True])

In [42]:
new_array

array([1, 2, 1])

In [43]:
(new_array).dtype

dtype('int64')

#### Array indexing

In [44]:
a

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971],
       [0.43857224, 0.0596779 , 0.39804426],
       [0.73799541, 0.18249173, 0.17545176]])

In [45]:
a[0]

array([0.69646919, 0.28613933, 0.22685145])

In [46]:
a[0,0]

0.6964691855978616

In [47]:
a[0,-1]

0.2268514535642031

In [48]:
a[0:2]

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646]])

In [49]:
a[0,1:3]

array([0.28613933, 0.22685145])

In [50]:
a[:,:]

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971],
       [0.43857224, 0.0596779 , 0.39804426],
       [0.73799541, 0.18249173, 0.17545176]])

#### Modifying a slice will modify the array

In [51]:
a[0,0]

0.6964691855978616

In [52]:
a[0,0] = 10

In [53]:
a

array([[10.        ,  0.28613933,  0.22685145],
       [ 0.55131477,  0.71946897,  0.42310646],
       [ 0.9807642 ,  0.68482974,  0.4809319 ],
       [ 0.39211752,  0.34317802,  0.72904971],
       [ 0.43857224,  0.0596779 ,  0.39804426],
       [ 0.73799541,  0.18249173,  0.17545176]])

#### Boolean indexing

In [54]:
print(a)

[[10.          0.28613933  0.22685145]
 [ 0.55131477  0.71946897  0.42310646]
 [ 0.9807642   0.68482974  0.4809319 ]
 [ 0.39211752  0.34317802  0.72904971]
 [ 0.43857224  0.0596779   0.39804426]
 [ 0.73799541  0.18249173  0.17545176]]


In [55]:
bool_idx = (a > 0.7)
bool_idx

array([[ True, False, False],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [False, False, False],
       [ True, False, False]])

In [56]:
print(a[bool_idx])
#print(a[a > 0.7]) # in a single expression

[10.          0.71946897  0.9807642   0.72904971  0.73799541]


#### Reshaping arrays

In [57]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

In [59]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Subarrays return views, not copies!

In [61]:
a

array([[10.        ,  0.28613933,  0.22685145],
       [ 0.55131477,  0.71946897,  0.42310646],
       [ 0.9807642 ,  0.68482974,  0.4809319 ],
       [ 0.39211752,  0.34317802,  0.72904971],
       [ 0.43857224,  0.0596779 ,  0.39804426],
       [ 0.73799541,  0.18249173,  0.17545176]])

In [62]:
# we take a slice of array "a" and store it in a new variable "a_chunk"
a_chunk = a[1:3, 0:2]
a_chunk

array([[0.55131477, 0.71946897],
       [0.9807642 , 0.68482974]])

In [63]:
# modifying "a_chung" also modifies "a"
a_chunk[0,0] = 0
print(a_chunk)
print("\n")
print(a)

[[0.         0.71946897]
 [0.9807642  0.68482974]]


[[10.          0.28613933  0.22685145]
 [ 0.          0.71946897  0.42310646]
 [ 0.9807642   0.68482974  0.4809319 ]
 [ 0.39211752  0.34317802  0.72904971]
 [ 0.43857224  0.0596779   0.39804426]
 [ 0.73799541  0.18249173  0.17545176]]


#### Creating copies

In [64]:
a_copy = a.copy()

In [65]:
# modifying a copy does not modify the original
a_copy[0,0] = 0
print(a_copy, "\n")
print(a)

[[0.         0.28613933 0.22685145]
 [0.         0.71946897 0.42310646]
 [0.9807642  0.68482974 0.4809319 ]
 [0.39211752 0.34317802 0.72904971]
 [0.43857224 0.0596779  0.39804426]
 [0.73799541 0.18249173 0.17545176]] 

[[10.          0.28613933  0.22685145]
 [ 0.          0.71946897  0.42310646]
 [ 0.9807642   0.68482974  0.4809319 ]
 [ 0.39211752  0.34317802  0.72904971]
 [ 0.43857224  0.0596779   0.39804426]
 [ 0.73799541  0.18249173  0.17545176]]


#### 3-D arrays

In [ ]:
b = np.random.random((5,2,3))
print(b)

### 4-D arrays

In [ ]:
c = np.random.random((2,3,4,5))
print(c)


### Operations:

- np.sum, np.multiply, np.power...

- np.mean, np.std...

In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])
x**y  # works with *, /, **  element wise 

Lists do not behave the same way: sum means concatenation

In [66]:
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [67]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print("x", "\n", x)
print("y", "\n", y)

x 
 [[1 2]
 [3 4]]
y 
 [[5 6]
 [7 8]]


In [68]:
print (x + y)

[[ 6  8]
 [10 12]]


In [69]:
# Mean of each column in matrix a
print(np.mean(a, axis=0))
  
# Mean of each row in matrix a
print(np.mean(a, axis=1))

# Mean of all the elements in the first two groups of array b
np.mean(b[:2])

[2.09157489 0.37929761 0.40557259]
[3.50433026 0.38085848 0.71550861 0.48811508 0.2987648  0.36531296]


2.0

In [70]:
# compute the standard deviation of this array, first using np.std() and then without using this function
np.random.seed(123)
rand = np.random.random(10)
rand

array([0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897,
       0.42310646, 0.9807642 , 0.68482974, 0.4809319 , 0.39211752])

In [71]:
squared_deviations = (rand - np.mean(rand))**2
squared_deviations

array([2.31861019e-02, 6.65949729e-02, 1.00709689e-01, 5.06291464e-05,
       3.07194386e-02, 1.46634887e-02, 1.90588864e-01, 1.97769054e-02,
       4.00277042e-03, 2.31288845e-02])

In [72]:
np.sqrt(squared_deviations.mean())

0.21758256938579879

In [73]:
new_array = np.array([[1,2],[3,4],[5,6]])

In [74]:
new_array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [75]:
new_array.T

array([[1, 3, 5],
       [2, 4, 6]])

#### Performance of numpy operations vs lists

In [76]:
from time import time

n = 1000000

start_time = time()

big_slow_list = []

for i in range(1, n):
    big_slow_list.append(i**3)

end_time = time()
    
print(end_time - start_time)

0.23732709884643555


In [77]:
n = 1000000

start_time = time()

big_fast_array = np.arange(1,n)**3

end_time = time()
    
print(end_time - start_time)

0.007495880126953125


#### Concatenate

In [82]:
first = np.array([[1,2,3],[4,5,6]])
second = np.array([[0,0,0,0], [9,9,9,9]])

In [83]:
first

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
second

array([[0, 0, 0, 0],
       [9, 9, 9, 9]])

In [85]:
np.concatenate([first, second])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

In [ ]:
np.concatenate([first, second], axis=1)

In [ ]:
one_dim = np.array([1,1,1])

In [ ]:
np.vstack([first, one_dim])

### Transpose

In [ ]:
print(first)

In [ ]:
print(first.T)

#### Splitting arrays

In [ ]:
hundred = np.array(range(1,101))

In [ ]:
hundred

In [ ]:
first_half, second_half = np.split(hundred, [50])

In [ ]:
first_half

In [ ]:
second_half